#!/usr/bin/env python3
"""Root-cause clustering over marathon attempts (STEP 19).

Reads results/marathon-state.json, normalizes each failed attempt's error
signature, clusters by (failure_category, normalized root cause) and ranks by
affected workloads + fixability. Writes reports/marathon-v2-root-causes.md.

Classification honesty: a cluster marked HARNESS/ENVIRONMENT/NETWORK is not an
AMD/OpenVINO compatibility failure; clusters marked UPSTREAM/COMPAT are.
"""

from __future__ import annotations

import re
import sys
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from ov_amd.scheduler import load_state  # noqa: E402

# category -> whether a failure here is plausibly an AMD/OpenVINO compatibility
# issue (True) or an environment/network/harness/upstream-infrastructure issue
# (False). Used to separate honest compatibility signals from campaign noise.
NON_COMPAT_CATEGORIES = {
    "NETWORK", "DOWNLOAD", "MODEL_ACCESS", "DEPENDENCY", "PACKAGE_CONFLICT",
    "TIMEOUT", "DISK_LIMIT", "RAM_LIMIT", "OOM", "EXTERNAL_SERVICE",
}

# normalized root-cause patterns over the last note / error head
PATTERNS: list[tuple[str, str]] = [
    (r"cannot import name 'hf_cache_home'|cannot import name 'cached_download'", "huggingface_hub API removed (old notebook pins import legacy API)"),
    (r"InvalidSchema|No connection adapters", "malformed URL after substitution corruption (v0.1-era or upstream typo)"),
    (r"unsupported (configuration )?key: FULL_DEVICE_NAME", "OpenVINO NPU device query unsupported on this stack"),
    (r"ncclCommResume|undefined symbol", "torch/NCCL binary incompatibility"),
    (r"optimum-cli", "optimum-cli broken/missing in environment"),
    (r"transformers-old|transformers-missing", "transformers version drift from notebook pins"),
    (r"protobuf-old|protobuf-missing", "protobuf version drift"),
    (r"ResolutionImpossible", "pip dependency resolution conflict"),
    (r"HfHubHTTPError|401|403|Access to model .* denied|gated repo", "model repo gated/unreachable on mirror"),
    (r"getaddrinfo failed|ConnectionError|timed out|RemoteDisconnected", "network host unreachable"),
    (r"CellTimeoutError|TimeoutExpired", "cell/wall timeout (heavy workload or stalled network)"),
    (r"Cannot allocate memory|MemoryError|std::bad_alloc", "out of memory"),
    (r"No module named", "missing python package (targeted install should remediate)"),
    (r"Failed to convert|Conversion|convert_model|ovc ", "OpenVINO model conversion failure"),
    (r"FULL_DEVICE_NAME|\bNPU\b", "NPU-specific API surface"),  # word-boundary: bare NPU substring matched the word "input")
]


def _norm_sig(text: str) -> str:
    text = re.sub(r"\x1b\[[0-9;]*m", "", text or "")
    for pat, sig in PATTERNS:
        if re.search(pat, text, re.I):
            return sig
    head = text.strip().splitlines()[-1][:120] if text.strip() else "(empty)"
    return f"other: {head}"


def main() -> int:
    state = load_state()
    clusters: dict[str, dict] = defaultdict(lambda: {"workloads": [], "category": Counter(), "compat": Counter()})

    for wid, rec in state.get("attempts", {}).items():
        for backend in ("cpu", "gpu"):
            r = rec.get(backend) or {}
            if r.get("status") != "FAILED":
                continue
            cat = r.get("failure_category") or "UNKNOWN"
            note = (r.get("notes") or [""])[-1]
            sig = _norm_sig(note)
            c = clusters.setdefault(f"{backend}:{cat}:{sig}", {"workloads": [], "category": Counter(), "compat": Counter()})
            c["workloads"].append(f"{wid}({backend})")
            c["category"][f"{backend}:{cat}"] += 1
            compat = "NON_COMPAT" if cat in NON_COMPAT_CATEGORIES else "COMPAT"
            c["compat"][compat] += 1

    ranked = sorted(clusters.items(), key=lambda kv: -len(kv[1]["workloads"]))
    total_failed = sum(len(c["workloads"]) for _, c in ranked)

    lines = [
        "# Marathon v2 Root Causes (generated by scripts/cluster_root_causes.py)",
        "",
        f"Generated: {datetime.now(timezone.utc).isoformat(timespec='seconds')}",
        f"Failed attempts clustered: **{total_failed}** into {len(ranked)} root-cause clusters",
        "",
        "| # | Cluster (backend:category:signature) | Affected | Class | Workloads |",
        "|---|---|---|---|---|",
    ]
    for i, (key, c) in enumerate(ranked, 1):
        n = len(c["workloads"])
        cls = "+".join(sorted(c["compat"]))
        wls = ", ".join(c["workloads"][:8]) + (f" … (+{n - 8})" if n > 8 else "")
        lines.append(f"| {i} | `{key}` | {n} | {cls} | {wls} |")

    non_compat = sum(len(c["workloads"]) for _, c in ranked if "NON_COMPAT" in c["compat"])
    lines += [
        "",
        f"Of {total_failed} failed attempts, {non_compat} fall in categories dominated by",
        "environment/network/infrastructure causes (NON_COMPAT) — these are not AMD",
        "OpenVINO compatibility verdicts. Shared harness/environment issues are fixed",
        "first, then affected workloads are retried with `python -m ov_amd marathon",
        "--cpu-only --retry-failed`.",
    ]
    out = REPO / "reports" / "marathon-v2-root-causes.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out.relative_to(REPO)}: {total_failed} failures -> {len(ranked)} clusters")
    return 0


if __name__ == "__main__":
    sys.exit(main())
