"""Mark legacy v0.1 green results as REVALIDATION_REQUIRED (v0.2 migration).

The validation methodology changed materially in v0.2 (Evidence Schema v2,
per-workload environment isolation, positive device proof, correctness
contracts, auditable repeatability). Historical v0.1 green results stay
visible and untouched as evidence, but they must not present themselves as
current compatibility results.

This script is idempotent and history-preserving: it only rewrites
results/marathon-state.json attempt records that are green under v1 evidence
(no schema_version field in their metrics.json), recording
historical_status / historical_evidence / revalidation_reasons.
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
STATE = REPO / "results" / "marathon-state.json"

REASONS = [
    "validation_schema_v2",
    "environment_isolation",
    "positive_device_proof",
    "correctness_contract",
]


def _utcnow() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def main() -> int:
    state = json.loads(STATE.read_text())
    migrated: list[dict] = []
    for wid, rec in state.get("attempts", {}).items():
        for backend, r in rec.items():
            if not isinstance(r, dict):
                continue
            if r.get("status") not in ("VERIFIED", "VERIFIED_WITH_LIMITATIONS"):
                continue
            if r.get("schema_version") == 2:
                continue  # already v2 evidence; nothing to migrate
            if r.get("status") == "REVALIDATION_REQUIRED":
                continue
            ev = r.get("evidence_dir") or ""
            rel = ev.replace(f"{REPO}/", "")
            mjson = REPO / rel / "metrics.json" if rel else None
            if mjson and mjson.exists():
                try:
                    if int(json.loads(mjson.read_text()).get("schema_version", 1)) == 2:
                        continue
                except (OSError, json.JSONDecodeError, ValueError):
                    pass
            r["historical_status"] = r["status"]
            r["historical_evidence"] = rel
            r["revalidation_reasons"] = REASONS
            r["status"] = "REVALIDATION_REQUIRED"
            r["updated"] = _utcnow()
            migrated.append({"workload": wid, "backend": backend, "historical_status": r["historical_status"]})
    STATE.write_text(json.dumps(state, indent=2))

    counts: dict[str, int] = {}
    for m in migrated:
        counts[m["backend"]] = counts.get(m["backend"], 0) + 1

    lines = [
        "# Revalidation Migration (generated by scripts/migrate_revalidation.py)",
        "",
        f"Run: {_utcnow()}",
        "",
        f"Legacy v0.1 green results marked REVALIDATION_REQUIRED: **{len(migrated)}**"
        f" (cpu: {counts.get('cpu', 0)}, gpu: {counts.get('gpu', 0)})",
        "",
        "Reasons recorded on every record:",
        "",
    ]
    lines += [f"- {r}" for r in REASONS]
    lines += ["", "| Workload | Backend | Historical status | Historical evidence |", "|---|---|---|---|"]
    for m in sorted(migrated, key=lambda x: (x["backend"], x["workload"])):
        rec = state["attempts"][m["workload"]][m["backend"]]
        lines.append(
            f"| {m['workload']} | {m['backend']} | {m['historical_status']} | `{rec.get('historical_evidence', '')}` |"
        )
    lines += [
        "",
        "Historical evidence directories are preserved unmodified; the records",
        "above are excluded from current compatibility claims until revalidated",
        "under Evidence Schema v2.",
    ]
    out = REPO / "reports" / "revalidation-migration.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"migrated {len(migrated)} records; report -> {out.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
